---
title: 'Final Report'
author: "Iman Byndloss, Leah Li, and Rachel Williams" 
date: "12/09/2024"
output: pdf_document
toc: true
---
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
setwd("/home/guest/ByndlossLiWilliams")

# Load your packages
library(tidyverse)
library(lubridate)
library(dplyr)
library(here)
library(ggplot2)

here()

# Set your ggplot theme
my_theme <- 

# Load your datasets
Daily_Species_Counts <- read.csv(
  file = here("./Data/Processed/Daily_Species_Counts.csv"),
  stringsAsFactors = TRUE) 

Monthly_Species_Counts <- read.csv(
  file = here("./Data/Processed/Monthly_Species_Counts.csv"),
  stringsAsFactors = TRUE) 

Daily_Merge <- read.csv(
  file = here("./Data/Processed/Daily_Merge.csv"),
  stringsAsFactors = TRUE) 

Monthly_Merge <- read.csv(
  file = here("./Data/Processed/Monthly_Merge.csv"),
  stringsAsFactors = TRUE) 
```

```


# Rationale and Research Questions

The upcoming analyses seek to answer the following research questions: Does the overall activity (daily and monthly) for mammalian species differ across three Davidson County parks (Beaman, Bells Bend, and Mill Creek)? And do any park attributes (i.e., classification, size and disruptive activities) have a significant impact on the activity of the two most common species? Assuming null hypotheses, there is no significant difference between overall daily and monthly activity for mammals in the three parks, and none of the tested park attributes significantly impact the activity of eastern gray squirrels and white-tailed deer. 

To describe the motivation behind this research, we are interested in understanding how different factors influence mammalian species activity in urban parks. Parks like Beaman, Bells Bend, and Mill Creek not only provide essential green spaces for humans but also serve as critical habitats for wildlife. Our curiosity lies in exploring how park attributes, such as size and unique features, shape species behavior over time. By understanding these dynamics, we hope to foster greater appreciation for biodiversity in urban environments and support park management practices. 


\newpage

# Dataset Information



\newpage

# Exploratory Analysis 



\newpage

# Analysis


<insert specific question here and add additional subsections for additional questions below, if needed>
Question 1: The first question we wanted to answer is whether daily and monthly species activity differs between the target parks. We looked at Beaman, Bell's Bend, and Mill's Creek Park.

Does species' daily and monthly activity differ between parks?  


Question 2: The second question we wanted to answer is what factors might be causing different activity levels between parks. This study focused on the size, classification, and disruptive activities of each park. We used Deer and squirrels for this analysis because they were the most abundant species at all three parks. 

What factors might be causing different activity levels between parks for WHite-tailed Deer and Grey Squirrels? Does classification, size, or disruptive activities at each park cause changes in activity levels?




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section>