---
title: "Data Exploration"
output:
  html_document: default
  pdf_document: default
date: "2024-11-26"
---

```{r setup, include=FALSE}
# Load relevant packages
library(tidyverse)
library(lubridate)
library(here)
library(ggplot2)
library(mapview)
library(cowplot)
library(sf)
```

## Exploring Species Data
```{r}
# Read relevant csv files into data frames
Daily_Species_Counts <- read.csv(
  file = here("./Data/Processed/Daily_Species_Counts.csv"),
  stringsAsFactors = TRUE) 

Monthly_Species_Counts <- read.csv(
  file = here("./Data/Processed/Monthly_Species_Counts.csv"),
  stringsAsFactors = TRUE) 

Full_Period_Species_Counts <- read.csv(
  file = here("./Data/Processed/Full_Period_Species_Counts.csv"),
  stringsAsFactors = TRUE) 

Daily_Merge <- read.csv(
  file = here("./Data/Processed/Daily_Merge.csv"),
  stringsAsFactors = TRUE) 

Monthly_Merge <- read.csv(
  file = here("./Data/Processed/Monthly_Merge.csv"),
  stringsAsFactors = TRUE) 
```

### Count adjusted over time

```{r}
# Ensure the Date and Month columns are classed correctly
Daily_Species_Counts$Date <- as.Date(Daily_Species_Counts$Date)
Monthly_Species_Counts$Month <- as.Date(paste0(Monthly_Species_Counts$Month, 
                                               "-01"))

# Ensure species in alphabetical order
# Generate and assign rainbow colors
# Apply sorted species factor to data sets
all_species <- sort(unique(Daily_Species_Counts$Species))
species_colors_rainbow <- rainbow(length(all_species))
species_colors <- setNames(species_colors_rainbow, all_species)
Daily_Species_Counts$Species <- factor(Daily_Species_Counts$Species, 
                                       levels = all_species)
Monthly_Species_Counts$Species <- factor(Monthly_Species_Counts$Species,
                                         levels = all_species)

# Filter daily and monthly data for each park
Beaman_Daily <- Daily_Species_Counts %>% filter(
  ParkName == "Alvin G. Beaman Park")
Beaman_Monthly <- Monthly_Species_Counts %>% filter(
  ParkName == "Alvin G. Beaman Park")
  
BellsBend_Daily <- Daily_Species_Counts %>% filter(
  ParkName == "Bells Bend Park")
BellsBend_Monthly <- Monthly_Species_Counts %>% filter(
  ParkName == "Bells Bend Park")
  
MillCreek_Daily <- Daily_Species_Counts %>% filter(
  ParkName == "Mill Creek Park")
MillCreek_Monthly <- Monthly_Species_Counts %>% filter(
  ParkName == "Mill Creek Park")

# Graph daily and monthly data for each park
BD.plot <- ggplot(Beaman_Daily, aes(x = Date, 
                                    y = CountAdjusted, 
                                    color = Species)) +
  geom_line() +
  scale_color_manual(values = species_colors) +
  labs(title = "Daily Activity Levels for Mammal Species in Beaman Park",
       x = "Date", 
       y = "Count Adjusted",
       color = "Species")
BM.plot <- ggplot(Beaman_Monthly, aes(x = Month, 
                                      y = CountAdjusted, 
                                      color = Species)) +
  geom_line() +
  scale_color_manual(values = species_colors) +
  labs(title = "Monthly Activity Levels for Mammal Species in Beaman Park",
       x = "Date", 
       y = "Count Adjusted",
       color = "Species")

BBD.plot <- ggplot(BellsBend_Daily, aes(x = Date, 
                                        y = CountAdjusted, 
                                        color = Species)) +
  geom_line() +
  scale_color_manual(values = species_colors) +
  labs(title = "Daily Activity Levels for Mammal Species in Bells Bend Park",
       x = "Date", 
       y = "Count Adjusted",
       color = "Species")
BBM.plot <- ggplot(BellsBend_Monthly, aes(x = Month, 
                                          y = CountAdjusted, 
                                          color = Species)) +
  geom_line() +
  scale_color_manual(values = species_colors) +
  labs(title = "Monthly Activity Levels for Mammal Species in Bells Bend Park",
       x = "Date", 
       y = "Count Adjusted",
       color = "Species")

MCD.plot <- ggplot(MillCreek_Daily, aes(x = Date, 
                                        y = CountAdjusted, 
                                        color = Species)) +
  geom_line() +
  scale_color_manual(values = species_colors) +
  labs(title = "Daily Activity Levels for Mammal Species in Mill Creek Park",
       x = "Date", 
       y = "Count Adjusted",
       color = "Species")
MCM.plot <- ggplot(MillCreek_Monthly, aes(x = Month, 
                                          y = CountAdjusted, 
                                          color = Species)) +
  geom_line() +
  scale_color_manual(values = species_colors) +
  labs(title = "Monthly Activity Levels for Mammal Species in Mill Creek Park",
       x = "Date", 
       y = "Count Adjusted",
       color = "Species")

# Create a function to reduce label sizes
adjust_labels <- function(plot) {
  plot +
    theme(plot.title = element_text(size = 8),
          axis.title.x = element_text(size = 6),
          axis.title.y = element_text(size = 6),
          axis.text.x = element_text(size = 6),
          axis.text.y = element_text(size = 6))
}

# Apply label adjustments to all plots
BD.plot <- adjust_labels(BD.plot)
BM.plot <- adjust_labels(BM.plot)
BBD.plot <- adjust_labels(BBD.plot)
BBM.plot <- adjust_labels(BBM.plot)
MCD.plot <- adjust_labels(MCD.plot)
MCM.plot <- adjust_labels(MCM.plot)

# Create a function to reduce legend size
adjust_legend <- function(plot) {
  plot +
    theme(legend.key.size = unit(0.2, "cm"),
          legend.text = element_text(size = 4),
          legend.title = element_text(size = 5))
}

# Apply legend adjustments to all plots
BD.plot <- adjust_legend(BD.plot)
BM.plot <- adjust_legend(BM.plot)
BBD.plot <- adjust_legend(BBD.plot)
BBM.plot <- adjust_legend(BBM.plot)
MCD.plot <- adjust_legend(MCD.plot)
MCM.plot <- adjust_legend(MCM.plot)

# Display daily and monthly plots together
plot_grid(BD.plot, BBD.plot, MCD.plot,
          ncol = 1) #vertical alignment of plots
plot_grid(BM.plot, BBM.plot, MCM.plot, 
          ncol = 1) #vertical alignment of plots
```

### Adjusted Deer Count Graphs

```{r}
# Filter data for species
Daily_Deer_Counts <- Daily_Species_Counts %>%
  filter(Species == "White-tailed Deer") %>%
   mutate(Date = as.Date(Date)) 

Monthly_Deer_Counts <- Monthly_Species_Counts %>%
  filter(Species == "White-tailed Deer") %>%
   mutate(Month = as.Date(Month)) 

# Graphs for species counts over time
# with coloring for species that matches the graphs above
ggplot(Daily_Deer_Counts, aes(x= Date, y= CountAdjusted, color = Species)) +
  geom_line() +
  scale_color_manual(values = species_colors) +
  facet_wrap(~ ParkName, ncol = 1) + 
  theme(legend.position = "none") +
  labs(title = "Daily Adjusted White-tailed Deer Counts Over Time", 
       y = "Species Count")

ggplot(Monthly_Deer_Counts, aes(x= Month, y= CountAdjusted, color = Species)) +
  geom_line() +
  scale_color_manual(values = species_colors) +
  facet_wrap(~ ParkName, ncol = 1) + 
  theme(legend.position = "none") +
  labs(title = "Monthly Adjusted White-tailed Deer Counts Over Time", 
       y = "Species Count") 

# Combined graphs in which coloring is based on park
DailyDeer.plot <- ggplot(Daily_Deer_Counts, aes(x= Date, y= CountAdjusted, 
                                  color = ParkName)) +
  geom_line() + 
  theme(legend.position = "none") +
  labs(title = "Daily Adjusted White-tailed Deer Counts Over Time", 
       y = "Species Count",
       color = "Park Name")

MonthlyDeer.plot <- ggplot(Monthly_Deer_Counts, aes(x= Month, y= CountAdjusted, 
                                    color = ParkName)) +
  geom_line() +  
  theme(legend.position = "none") +
  labs(title = "Monthly Adjusted White-tailed Deer Counts Over Time", 
       y = "Species Count",
       color = "Park Name") 

# Extract the legend
legend <- cowplot::get_legend(
  ggplot(Monthly_Deer_Counts, aes(x = Month, y = CountAdjusted, 
                                  color = ParkName)) +
    geom_line() +
    theme_minimal() +
    theme(
      legend.key.size = unit(0.5, "cm"),
      legend.text = element_text(size = 6),
      legend.title = element_text(size = 7)
    ) +
    labs(color = "Park Name"))

# Display daily and monthly plots together
plot_grid(DailyDeer.plot, MonthlyDeer.plot, legend,
          ncol = 1, #vertical alignment of plots
          rel_heights = c(1, 1, 0.4)) 
```

### Adjusted Squirrel Count Graphs

```{r}
# Filter data for species
Daily_Squirrel_Counts <- Daily_Species_Counts %>%
  filter(Species == "Eastern Gray Squirrel") %>%
   mutate(Date = as.Date(Date)) 

Monthly_Squirrel_Counts <- Monthly_Species_Counts %>%
  filter(Species == "Eastern Gray Squirrel") %>%
   mutate(Month = as.Date(Month)) 

# Graphs for species counts over time
# with coloring for species that matches the graphs above
ggplot(Daily_Squirrel_Counts, aes(x= Date, y= CountAdjusted, color = Species)) +
  geom_line() +
  scale_color_manual(values = species_colors) +
  facet_wrap(~ ParkName, ncol = 1) + 
  theme(legend.position = "none") +
  labs(title = "Daily Adjusted Eastern Gray Squirrel Counts Over Time", 
       y = "Species Count")

ggplot(Monthly_Squirrel_Counts, aes(x= Month, y= CountAdjusted, color = Species)) +
  geom_line() +
  scale_color_manual(values = species_colors) +
  facet_wrap(~ ParkName, ncol = 1) + 
  theme(legend.position = "none") +
  labs(title = "Monthly Adjusted Eastern Gray Squirrel Counts Over Time", 
       y = "Species Count") 

# Combined graphs in which coloring is based on park
DailySquirrel.plot <- ggplot(Daily_Squirrel_Counts, aes(x= Date, 
                                                        y= CountAdjusted, 
                                                        color = ParkName)) +
  geom_line() + 
  theme(legend.position = "none") +
  labs(title = "Daily Adjusted Eastern Gray Squirrel Counts Over Time", 
       y = "Species Count",
       color = "Park Name")

MonthlySquirrel.plot <- ggplot(Monthly_Squirrel_Counts, aes(x= Month, 
                                                            y= CountAdjusted, 
                                                            color = ParkName)) +
  geom_line() + 
  theme(legend.position = "none") +
  labs(title = "Monthly Adjusted Eastern Gray Squirrel Counts Over Time", 
       y = "Species Count",
       color = "Park Name") 

# Extract the legend
legend <- cowplot::get_legend(
  ggplot(Monthly_Squirrel_Counts, aes(x = Month, y = CountAdjusted, 
                                  color = ParkName)) +
    geom_line() +
    theme_minimal() +
    theme(
      legend.key.size = unit(0.5, "cm"),
      legend.text = element_text(size = 6),
      legend.title = element_text(size = 7)
    ) +
    labs(color = "Park Name"))

# Display daily and monthly plots together
plot_grid(DailySquirrel.plot, MonthlySquirrel.plot, legend,
          ncol = 1, #vertical alignment of plots
          rel_heights = c(1, 1, 0.4))
```

### Count adjusted per species

```{r}
# Graph full period data
FP.plot <- ggplot(Full_Period_Species_Counts, aes(x = Species, 
                                                  y = CountAdjusted, 
                                                  color = ParkName)) +
  geom_col(position = "dodge") + #ensures bars do not overlap
  labs(title = "Total Counts for Species Across Parks During the Study Period",
       x = "Species", 
       y = "Count Adjusted",
       color = "Park Name") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) #tilts species names
FP.plot
```

### More Graphs
```{r}
#Draft plots, will fix as needed 

#Most common species from monthly data
ggplot(Monthly_Species_Counts, aes(x=Species, y=CountAdjusted, fill=Species)) +geom_bar(stat = "identity") +facet_wrap(~ ParkName) + theme(legend.text = element_text(size = 6),        # Smaller legend text
        legend.title = element_text(size = 8),       # Smaller legend title
        legend.key.size = unit(0.5, "cm"),            # Smaller legend keys (color boxes)
        legend.key.width = unit(1, "cm"),             # Adjust width of legend keys
        legend.position = "bottom",                   # Move legend to the bottom
        legend.spacing = unit(0.3, "cm"),axis.title.x = element_blank(),               # Remove x-axis label
    axis.text.x = element_blank() ) +
  labs(y = "Species Count")

```


## Exploring Spatial Data
```{r}
# Read relevant csv file into data frame
Park_Attributes <- st_read(
  '~/ByndlossLiWilliams/Data/Processed/Park_Attributes.shp')

# Map parks with attributes with color code based on park name
mapView(Park_Attributes, zcol = "Name", legend.title = "Park Name")

# Plot parks on coordinate graph with color code based on park name
ggplot(data = Park_Attributes) +
  geom_sf(aes(fill = Name), color = "black", lwd = 0.3) +
  labs(title = "A coordinate graph of parks", fill = "Park Name")
```